config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :coctails

   root 'coctails#index'

end

app/models/coctail.rb
class Coctail < ActiveRecord::Base
belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 has_many :coctails
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
end

app/controllers/coctails_controller.rb
class CoctailsController < ApplicationController
  before_action :set_coctail, only: [:show, :edit, :update, :destroy]

  # GET /coctails
  # GET /coctails.json
  def index
    @coctails = Coctail.all
    
    #if current_user.admin == false
    #    current_user.admin = true
    #    current_user.save
    #end
  end

  # GET /coctails/1
  # GET /coctails/1.json
  def show
  end

  # GET /coctails/new
  def new
    @coctail = Coctail.new
  end

  # GET /coctails/1/edit
  def edit
  end

  # POST /coctails
  # POST /coctails.json
  def create
    @coctail = Coctail.new(coctail_params)

    respond_to do |format|
      if @coctail.save
        format.html { redirect_to @coctail, notice: 'Coctail was successfully created.' }
        format.json { render :show, status: :created, location: @coctail }
      else
        format.html { render :new }
        format.json { render json: @coctail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coctails/1
  # PATCH/PUT /coctails/1.json
  def update
    respond_to do |format|
      if @coctail.update(coctail_params)
        format.html { redirect_to @coctail, notice: 'Coctail was successfully updated.' }
        format.json { render :show, status: :ok, location: @coctail }
      else
        format.html { render :edit }
        format.json { render json: @coctail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coctails/1
  # DELETE /coctails/1.json
  def destroy
    @coctail.destroy
    respond_to do |format|
      format.html { redirect_to coctails_url, notice: 'Coctail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coctail
      @coctail = Coctail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coctail_params
      params.require(:coctail).permit(:ime, :sestavine, :opis)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coctails_helper.rb
module CoctailsHelper
end

app/views/coctails/_form.html.erb
<%= form_for(@coctail) do |f| %>
  <% if @coctail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coctail.errors.count, "error") %> prohibited this coctail from being saved:</h2>

      <ul>
      <% @coctail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ime %><br>
    <%= f.text_field :ime %>
  </div>
  <div class="field">
    <%= f.label :sestavine %><br>
    <%= f.text_area :sestavine %>
  </div>
  <div class="field">
    <%= f.label :opis %><br>
    <%= f.text_area :opis %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <div>
   <%= form_for @coctail, :html =>{:multipart =>true} do |f| %>
                       <%= f.file_field :image %><br>
                 			 <%= f.button :submit %>
                     <% end %>
  </div>

<% end %>

app/views/coctails/edit.html.erb
<h1>Editing Coctail</h1>

<%= render 'form' %>

<%= link_to 'Show', @coctail %> |
<%= link_to 'Back', coctails_path %>

app/views/coctails/index.html.erb
<h1>Listing Coctails</h1>

<b id="uporabnik"><%= current_user.email%></b>
<br>
<br>
<b id="uporabnik"><%= link_to('Logout', destroy_user_session_path, method: :delete) %></b>
<table>
  <thead>
    <tr>
      <th>Ime</th>
      <th>Sestavine</th>
      <th>Opis</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coctails.each do |coctail| %>
      <tr>
        <td><%= coctail.ime %></td>
        <td>
            <% list = coctail.sestavine %>
            <% arr = list.split(" ") %>
            <% arr.each do |result| %>
                <%= result %><br>
            <% end %>
        </td>
        
        <td><%= coctail.opis %></td>
        <td id="gumb" ><%= link_to 'Show', coctail %></td>
        <% if current_user.admin == true %>
            <td><%= link_to 'Edit', edit_coctail_path(coctail) %></td>
            <td ><%= link_to 'Destroy', coctail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br >


<span class="gumbek"><%= link_to 'New Coctail', new_coctail_path %></span>

app/views/coctails/new.html.erb
<h1>New Coctail</h1>

<%= render 'form' %>

<%= link_to 'Back', coctails_path %>

app/views/coctails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ime:</strong>
  <%= @coctail.ime %>
</p>

<p>
  <strong>Sestavine:</strong>
  <%= @coctail.sestavine %>
</p>

<p>
  <strong>Opis:</strong>
  <%= @coctail.opis %>
</p>

<%= link_to 'Edit', edit_coctail_path(@coctail) %> |
<%= link_to 'Back', coctails_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Koktails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>